# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\86178\Desktop\MySql_Work\ui\xiaoshou.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(643, 397)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(160, 10, 331, 51))
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(50, 50, 541, 181))
        self.textBrowser.setObjectName("textBrowser")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(110, 250, 131, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 250, 61, 31))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 290, 131, 31))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(50, 290, 61, 31))
        self.label_3.setObjectName("label_3")
        self.jiru = QtWidgets.QPushButton(Form)
        self.jiru.setGeometry(QtCore.QRect(40, 340, 101, 31))
        self.jiru.setObjectName("jiru")
        self.jiesuan = QtWidgets.QPushButton(Form)
        self.jiesuan.setGeometry(QtCore.QRect(460, 280, 141, 81))
        self.jiesuan.setObjectName("jiesuan")
        self.shanchu = QtWidgets.QPushButton(Form)
        self.shanchu.setGeometry(QtCore.QRect(170, 340, 101, 31))
        self.shanchu.setObjectName("shanchu")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">销售系统</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "商品标号"))
        self.label_3.setText(_translate("Form", "商品数量"))
        self.jiru.setText(_translate("Form", "计入"))
        self.jiesuan.setText(_translate("Form", "结算"))
        self.shanchu.setText(_translate("Form", "删除"))
